# Site settings
title: O'Sweet Bakeshop
email: spence.couture@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "NH Bakeshop or something here"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 297045 #80B3FF
  primary-rgb: "128,179,255"
  secondary: 2E933C #FD6E8A
  secondary-dark: fa7921 #A2122F

# Footer settings
footer:
  copyright: O'Sweet Bakeshop
  location: Location
  social: Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/osweetnh/

# Postal address (add as many lines as necessary)
address:
  - line: 3 Longview Drive
  - line: Hampstead, NH 03841

# Credits content
credits: 'This site was written by the legend Spencer'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
