# Site settings
title: O'Sweet Bakeshop
email: osweetnh@gmail.com
description: "NH Bakeshop"
keywords: "NH, bakeshop, bakery, Hampstead, Couture, osweet"
skills: "NH Bakeshop"
meta_author: Couture Kathleen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9678b0
  secondary: 4e3e5b
  secondary-dark: 92b078

# Footer settings
footer:
  copyright: O'Sweet Bakeshop
  location: Location
  social: Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/osweetnh/

# Postal address (add as many lines as necessary)
address:
  - line: 3 Longview Drive
  - line: Hampstead, NH 03841

# Credits content
credits: 'This site was written by the legend Spencer'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

menu:
  - name: "The Classic"
  - name: "The Nutty Classic"
  - name: "The Chocolate Lovers Classic"
  - name: "P.B.C.C."
  - name: "Not Your Grammy's Oatmeal Raisin Cookie"
  - name: "Celebration!"
  - name: "Lime in de Coconut"
  - name: "V.I.P."
  - name: "Lemon Dot"
  - name: "Strawberries n' Cream"
  - name: "Apples and Spice and Everything Nice"
  - name: "M.R.F.M. Brownie Bites"
  - name: "Dad's Heritage Hermits"
  - name: "Brownut Doughnie"