# Site settings
title: O'Sweet Bakeshop
email: osweetnh@gmail.com
description: "NH Bakeshop"
baseurl: osweetnh.com
keywords: "NH, bakeshop, bakery, Hampstead, Couture, osweet"
skills: "Hampstead NH Bakeshop"
meta_author: Couture Kathleen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9678b0
  secondary: 4e3e5b
  secondary-dark: 92b078

# Footer settings
footer:
  copyright: O'Sweet Bakeshop
  location: Location
  social: Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/osweetnh/
  - title: facebook
    url: https://www.facebook.com/o.sweetbakeshop/

# Postal address (add as many lines as necessary)
address:
  - line: 3 Longview Drive
  - line: Hampstead, NH 03841

# Credits content
credits: 'This site was written by the legend Spencer'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

menu:
  - name: "The Classic"
    description: "Can't go wrong with a giant chocolate chip cookie!  All you need is a tall glass of cow juice and ample time for 'just one more.'"
  - name: "The Nutty Classic"
    description: "Nut lovers will crave this classic chocolate chip that gets a flavor and texture boost with pecans."
  - name: "The Chocolate Lovers Classic"
    description: "Too. Much. Chocolate.  Said, NO ONE EVER!  Your favorite chocolate chips get the chocolate cookie treatment to stamp out a chocolate lover's cravings."
  - name: "P.B.C.C."
    description: "Peanut Butter Chocolate Chip.  Need we say more?"
  - name: "Not Your Grammy's Oatmeal Raisin Cookie"
    description: "Grammy's classic gets a little flavor boost infused with warm spices .  This one's perfect for your morning cuppa!"
  - name: "'You Had Me at Nutella or Hella Nutella'"
    description: "Who could resist this decadent chocolate cookie stuffed with ooey, gooey, hazelnut spread?"
  - name: "P.B.Y Not?"
    description: "Chocolate Cookie?  Check.  Peanut Butter center?  Check. So, whY Not?"
  - name: "Celebration!"
    description: "It's someone's birthday somewhere, right?!  But who even needs a birthday to celebrate?  Your tastebuds and tummy will celebrate YOU for the fun burst of sprinkles in every bite."
  - name: "Lime in de Coconut"
    description: "Just what the Doctor ordered 'to relieve this belly ache!'  A coconut lime cookie with a powdered sugar crinkle - that'll cure what ails for sure!"
  - name: "V.I.P."
    description: "Take a box of these to your next Velvet Rope event and you'll be sure to be sent to the front of the line like a V.I.P.  Classic Red Velvet gets the cookie treatment with some sweet white chips."
  - name: "Lemon Dot"
    description: "Sweet and sour in all the right ways, this lemony cookie gets dotted by some white chips."
  - name: "Strawberries n' Cream"
    description: "A classic pairing in a cookie that can't be beat: a tender strawberry cookie bursting with white chips"
  - name: "Apples and Spice and Everything Nice"
    description: "This cookie is reminiscent of a handheld apple pie where the white chips make it a la mode.  No spoon needed!"
  - name: "M.R.F.M. Brownie Bites"
    description: "Sometimes mini just means Make Room For More!  This downsized brownie classic adds a little bitty drizzle for pizzazz, but don't let the name fool you -- it may be mini, but it packs a BIG chocolaty flavor punch!"
  - name: "Dad's Heritage Hermits"
    description: "A New England regional classic, this raisin studded, warm-spiced cookie will either take you back to your local roots or introduce you to a new craving.  My Dad's favorite childhood treat will soon be yours!"
  - name: "Brownut Doughnie"
    description: "Is it a brownie?  Is it a doughnut?  Whatever you call it, this chocolaty, peanut butter explosion will tempt your tastebuds.  We dare you to eat just one."
  - name: "New Englander Foreva!"
    description: "Real maple syrup purists, rejoice!  Made with pure, dark amber, grade A, local maple syrup, this maple walnut cookie will keep New England Sugaring Season in your heart Foreva!"
  - name: "Biscotti Bliss"
    description: "Twice baked and paired with two distinct elements: Tangy Cranberries and Nutty Pistachios, this is the perfect treat to share with your bestie.  My Mom and I enjoyed precious time spent indulging this crsipy delight together, and we know you will do the same with your favorite twosome."
  - name: "P 3"
    description: "P to the third power: A tender peanut butter cookie studded with Peanuts, Pretzels and Peanut Butter Cups.  You'll think you just hit the trifecta when you savor this perfectly balanced salty sweet combo."
  - name: "Want S'More?"
    description: "All your campfire favorites combined into one sinfully delicious delight.  The only thing missing is the stick."
  - name: "Totally Cereal"
    description: "Bowls and spoons need not apply. We are 'Totally Cereal' when we say just add a glass of milk.  One bite of this gem adorned with Fruity Pebbles and white chips, and you'll be instantly transported back to lazy Saturday morning cartoons and cereal."
  - name: "So Extra"
    description: "Cookies inside cookies? You bet!  This showstopper is teeming with chocolate cream cookies, mini chocolate chips, cookies and cream candy bars and white chips.  Nibble off each nugget or take a big 'ol chomp; You do you - we won't judge!"
